# Generated by Django 4.2.9 on 2024-01-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_is_active_collection_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topcategory',
            name='images',
            field=models.ImageField(null=True, upload_to='top-category', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='topcategory',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
