# Generated by Django 4.2.9 on 2024-01-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_topcategory_images_topcategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topcategory',
            old_name='images',
            new_name='image',
        ),
    ]
